from PyQt5 import QtCore, QtGui, QtWidgets


class Keyboard(object):
    def setupUi(self, Dialog, keyFunction,delFunction):
        self.isUpper = True
        Dialog.setObjectName("Dialog")
        Dialog.resize(675, 235)
        Dialog.setStyleSheet("QWidget{\n"
"    background-color: #404040;}\n"
"QPushButton{\n"
"    color: #FFFFCC; \n"
"    font: bold 30px; \n"
"    height: 50 px;\n"
"    width: 50 px;\n"
"    background-color: #006600;\n"
"    border-style: inset;\n"
"    border-color:black;\n"
"    border-width: 1px;}")
        self.lL = []
        Dialog.setWindowFlags(QtCore.Qt.FramelessWindowHint | QtCore.Qt.Popup)
        self.q = QtWidgets.QPushButton(Dialog)
        self.q.setObjectName("q")
        self.q.move(10, 10)
        self.lL.append(self.q)
        self.w = QtWidgets.QPushButton(Dialog)
        self.w.setObjectName("w")
        self.w.move(65, 10)
        self.lL.append(self.w)
        self.e = QtWidgets.QPushButton(Dialog)
        self.e.setObjectName("e")
        self.e.move(120, 10)
        self.lL.append(self.e)
        self.r = QtWidgets.QPushButton(Dialog)
        self.r.setObjectName("r")
        self.r.move(175, 10)
        self.lL.append(self.r)
        self.t = QtWidgets.QPushButton(Dialog)
        self.t.setObjectName("t")
        self.t.move(230, 10)
        self.lL.append(self.t)
        self.z = QtWidgets.QPushButton(Dialog)
        self.z.setObjectName("z")
        self.z.move(285, 10)
        self.lL.append(self.z)
        self.u = QtWidgets.QPushButton(Dialog)
        self.u.setObjectName("u")
        self.u.move(340, 10)
        self.lL.append(self.u)
        self.i = QtWidgets.QPushButton(Dialog)
        self.i.setObjectName("i")
        self.i.move(395, 10)
        self.lL.append(self.i)
        self.o = QtWidgets.QPushButton(Dialog)
        self.o.setObjectName("o")
        self.o.move(450, 10)
        self.lL.append(self.o)
        self.p = QtWidgets.QPushButton(Dialog)
        self.p.setObjectName("p")
        self.p.move(505, 10)
        self.lL.append(self.p)
        self.ue = QtWidgets.QPushButton(Dialog)
        self.ue.setObjectName("ü")
        self.ue.move(560, 10)
        self.lL.append(self.ue)
        self.sz = QtWidgets.QPushButton(Dialog)
        self.sz.setObjectName("ß")
        self.sz.move(615, 10)
        self.a = QtWidgets.QPushButton(Dialog)
        self.a.setObjectName("a")
        self.a.move(35, 65)
        self.lL.append(self.a)
        self.s = QtWidgets.QPushButton(Dialog)
        self.s.setObjectName("s")
        self.s.move(90, 65)
        self.lL.append(self.s)
        self.d = QtWidgets.QPushButton(Dialog)
        self.d.setObjectName("d")
        self.d.move(145, 65)
        self.lL.append(self.d)
        self.f = QtWidgets.QPushButton(Dialog)
        self.f.setObjectName("f")
        self.f.move(200, 65)
        self.lL.append(self.f)
        self.g = QtWidgets.QPushButton(Dialog)
        self.g.setObjectName("g")
        self.g.move(255, 65)
        self.lL.append(self.g)
        self.h = QtWidgets.QPushButton(Dialog)
        self.h.setObjectName("h")
        self.h.move(310, 65)
        self.lL.append(self.h)
        self.j = QtWidgets.QPushButton(Dialog)
        self.j.setObjectName("j")
        self.j.move(365, 65)
        self.k = QtWidgets.QPushButton(Dialog)
        self.k.setObjectName("k")
        self.k.move(420, 65)
        self.lL.append(self.k)
        self.l = QtWidgets.QPushButton(Dialog)
        self.l.setObjectName("l")
        self.l.move(475, 65)
        self.lL.append(self.l)
        self.oe = QtWidgets.QPushButton(Dialog)
        self.oe.setObjectName("ö")
        self.oe.move(530, 65)
        self.lL.append(self.oe)
        self.ae = QtWidgets.QPushButton(Dialog)
        self.ae.setObjectName("ä")
        self.ae.move(585, 65)
        self.lL.append(self.ae)
        self.y = QtWidgets.QPushButton(Dialog)
        self.y.setObjectName("y")
        self.y.move(60, 120)
        self.lL.append(self.y)
        self.x = QtWidgets.QPushButton(Dialog)
        self.x.setObjectName("x")
        self.x.move(115, 120)
        self.lL.append(self.x)
        self.c = QtWidgets.QPushButton(Dialog)
        self.c.setObjectName("c")
        self.c.move(170, 120)
        self.lL.append(self.c)
        self.v = QtWidgets.QPushButton(Dialog)
        self.v.setObjectName("v")
        self.v.move(225, 120)
        self.lL.append(self.v)
        self.b = QtWidgets.QPushButton(Dialog)
        self.b.setObjectName("b")
        self.b.move(280, 120)
        self.lL.append(self.b)
        self.n = QtWidgets.QPushButton(Dialog)
        self.n.setObjectName("n")
        self.n.move(335, 120)
        self.lL.append(self.n)
        self.m = QtWidgets.QPushButton(Dialog)
        self.m.setObjectName("m")
        self.m.move(390, 120)
        self.lL.append(self.m)
        self.strich = QtWidgets.QPushButton(Dialog)
        self.strich.setObjectName("strich")
        self.strich.move(445, 120)
        self.space = QtWidgets.QPushButton(Dialog)
        self.space.setObjectName("space")
        self.space.setGeometry(QtCore.QRect(170,175,300,50))
        self.delete = QtWidgets.QPushButton(Dialog)
        self.delete.setObjectName("delete")
        self.delete.setGeometry(QtCore.QRect(565,175,100,50))
        self.shift = QtWidgets.QPushButton(Dialog)
        self.shift.setObjectName("shift")
        self.shift.setGeometry(QtCore.QRect(5,175,100,50))
        self.shift.clicked.connect(self.changeCase)

        self.a.clicked.connect(lambda: keyFunction(self.a.text()))
        self.b.clicked.connect(lambda: keyFunction(self.b.text()))
        self.c.clicked.connect(lambda: keyFunction(self.c.text()))
        self.d.clicked.connect(lambda: keyFunction(self.d.text()))
        self.e.clicked.connect(lambda: keyFunction(self.e.text()))
        self.f.clicked.connect(lambda: keyFunction(self.f.text()))
        self.g.clicked.connect(lambda: keyFunction(self.g.text()))
        self.h.clicked.connect(lambda: keyFunction(self.h.text()))
        self.i.clicked.connect(lambda: keyFunction(self.i.text()))
        self.j.clicked.connect(lambda: keyFunction(self.j.text()))
        self.k.clicked.connect(lambda: keyFunction(self.k.text()))
        self.l.clicked.connect(lambda: keyFunction(self.l.text()))
        self.m.clicked.connect(lambda: keyFunction(self.m.text()))
        self.n.clicked.connect(lambda: keyFunction(self.n.text()))
        self.o.clicked.connect(lambda: keyFunction(self.o.text()))
        self.p.clicked.connect(lambda: keyFunction(self.p.text()))
        self.q.clicked.connect(lambda: keyFunction(self.q.text()))
        self.r.clicked.connect(lambda: keyFunction(self.r.text()))
        self.s.clicked.connect(lambda: keyFunction(self.s.text()))
        self.t.clicked.connect(lambda: keyFunction(self.t.text()))
        self.u.clicked.connect(lambda: keyFunction(self.u.text()))
        self.v.clicked.connect(lambda: keyFunction(self.v.text()))
        self.w.clicked.connect(lambda: keyFunction(self.w.text()))
        self.x.clicked.connect(lambda: keyFunction(self.x.text()))
        self.y.clicked.connect(lambda: keyFunction(self.y.text()))
        self.z.clicked.connect(lambda: keyFunction(self.z.text()))
        self.ae.clicked.connect(lambda: keyFunction(self.ae.text()))
        self.oe.clicked.connect(lambda: keyFunction(self.oe.text()))
        self.ue.clicked.connect(lambda: keyFunction(self.ue.text()))
        self.sz.clicked.connect(lambda: keyFunction(self.sz.text()))
        self.strich.clicked.connect(lambda : keyFunction('-'))
        self.space.clicked.connect(lambda : keyFunction(' '))
        self.delete.clicked.connect(delFunction)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.a.setText(_translate("Dialog", "A"))
        self.b.setText(_translate("Dialog", "B"))
        self.c.setText(_translate("Dialog", "C"))
        self.d.setText(_translate("Dialog", "D"))
        self.e.setText(_translate("Dialog", "E"))
        self.f.setText(_translate("Dialog", "F"))
        self.g.setText(_translate("Dialog", "G"))
        self.h.setText(_translate("Dialog", "H"))
        self.i.setText(_translate("Dialog", "I"))
        self.j.setText(_translate("Dialog", "J"))
        self.k.setText(_translate("Dialog", "K"))
        self.l.setText(_translate("Dialog", "L"))
        self.m.setText(_translate("Dialog", "M"))
        self.n.setText(_translate("Dialog", "N"))
        self.o.setText(_translate("Dialog", "O"))
        self.p.setText(_translate("Dialog", "P"))
        self.q.setText(_translate("Dialog", "Q"))
        self.r.setText(_translate("Dialog", "R"))
        self.s.setText(_translate("Dialog", "S"))
        self.t.setText(_translate("Dialog", "T"))
        self.u.setText(_translate("Dialog", "U"))
        self.v.setText(_translate("Dialog", "V"))
        self.w.setText(_translate("Dialog", "W"))
        self.x.setText(_translate("Dialog", "X"))
        self.y.setText(_translate("Dialog", "Y"))
        self.z.setText(_translate("Dialog", "Z"))
        self.sz.setText(_translate("Dialog", "ß"))
        self.ae.setText(_translate("Dialog", "Ä"))
        self.oe.setText(_translate("Dialog", "Ö"))
        self.ue.setText(_translate("Dialog", "Ü"))
        self.space.setText(_translate("Dialog", "space"))
        self.delete.setText(_translate("Dialog", "←"))
        self.strich.setText(_translate("Dialog", "-"))
        self.shift.setText(_translate("Dialog", "↑"))

    def createSlot (self,obj , function):
        return function(obj.text())
    
    def changeCase(self) :
        if self.isUpper :
            for l in self.lL :
                l.setText(l.text().lower())
            self.isUpper = False
        else :
            for l in self.lL :
                l.setText(l.text().upper())
            self.isUpper = True

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Keyboard()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
